--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ArchDev2/SimpleShop
build-by-default: true
branches:
- main
projects:
  SimpleShop:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...
